template:
  - name: "🚄 Business Trip Template"
    description: "Milestone: Business Trip"
    title: "[Business Trip]"
    labels: ["owner: tokuhara-j"]
    projects: ["project2024"]

    body:
      - type: input
        attributes:
          label: Departure Date
          placeholder: e.g., 20240101
        validations:
          required: true
      - type: input
        attributes:
          label: Business Trip Name
          placeholder: e.g., NABLAS visit, International Robotics Expo
        validations:
          required: true
      - type: dropdown
        attributes:
          label: Traveler
          options:
            - taikiinoue45
            - duke029
            - kasa09
            - Shuiiku20
            - tokuhara-j
            - PranavKai
            - shimoi226
        default: 0  # Default index
        validations:
          required: true
      - type: input
        attributes:
          label: Purpose
          placeholder: e.g., Meeting attendance, Client visit
        validations:
          required: true
      - type: input
        attributes:
          label: Duration
          placeholder: e.g., 20240101 - 20240105
        validations:
          required: true
      - type: input
        attributes:
          label: Departure Location
          placeholder: e.g., Tokyo
      - type: input
        attributes:
          label: End Condition
          placeholder: e.g., Reached home at 8:00 pm
      - type: input
        attributes:
          label: Budget Code (optional)
          placeholder: e.g., ABC-123
