name: Delete Failed Workflow Runs

on:
  workflow_dispatch:

jobs:
  delete_failed_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Failed Runs
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: runs } = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file_name: '.github/workflows/sample_workflow.yml', // Replace with your workflow file name
              status: 'completed',
              conclusion: 'failure'
            });
            for (const run of runs.workflow_runs) {
              await github.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });
              console.log(`Deleted failed workflow run ${run.id}`);
            }
